version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    networks:
      - laravel-network
    depends_on:
      - mysql
      - redis
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000"
    env_file:
      - .env

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue
    networks:
      - laravel-network
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- php artisan queue:work --sleep=3 --tries=3"
    env_file:
      - .env

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-scheduler
    networks:
      - laravel-network
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    command: >
      sh -c "while :; do php artisan schedule:run; sleep 60; done"
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:6.0
    container_name: laravel-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
